steps:
  # Build backend image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'asia-south2-docker.pkg.dev/$PROJECT_ID/myfirstproject-repo/backend:$COMMIT_SHA'
      - '-t'
      - 'asia-south2-docker.pkg.dev/$PROJECT_ID/myfirstproject-repo/backend:latest'
      - './backend'
    id: 'build-backend'

  # Build frontend image with backend URL
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'asia-south2-docker.pkg.dev/$PROJECT_ID/myfirstproject-repo/frontend:$COMMIT_SHA'
      - '-t'
      - 'asia-south2-docker.pkg.dev/$PROJECT_ID/myfirstproject-repo/frontend:latest'
      - '--build-arg'
      - 'VITE_API_BASE_URL=${_BACKEND_URL}/api'
      - './frontend'
    id: 'build-frontend'

  # Push backend image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - '--all-tags'
      - 'asia-south2-docker.pkg.dev/$PROJECT_ID/myfirstproject-repo/backend'
    id: 'push-backend'

  # Push frontend image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - '--all-tags'
      - 'asia-south2-docker.pkg.dev/$PROJECT_ID/myfirstproject-repo/frontend'
    id: 'push-frontend'

  # Deploy backend to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'backend'
      - '--image=asia-south2-docker.pkg.dev/$PROJECT_ID/myfirstproject-repo/backend:$COMMIT_SHA'
      - '--region=asia-south2'
      - '--platform=managed'
      - '--allow-unauthenticated'
      - '--add-cloudsql-instances=${_CLOUD_SQL_CONNECTION_NAME}'
      - '--set-env-vars=DB_SOCKET_PATH=/cloudsql/${_CLOUD_SQL_CONNECTION_NAME}'
      - '--set-secrets=DB_USER=DB_USER:latest,DB_PASSWORD=DB_PASSWORD:latest,DB_NAME=DB_NAME:latest'
      - '--max-instances=10'
      - '--min-instances=0'
      - '--memory=512Mi'
    id: 'deploy-backend'

  # Deploy frontend to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'frontend'
      - '--image=asia-south2-docker.pkg.dev/$PROJECT_ID/myfirstproject-repo/frontend:$COMMIT_SHA'
      - '--region=asia-south2'
      - '--platform=managed'
      - '--allow-unauthenticated'
      - '--max-instances=10'
      - '--min-instances=0'
      - '--memory=256Mi'
    id: 'deploy-frontend'

substitutions:
  _CLOUD_SQL_CONNECTION_NAME: 'PROJECT_ID:REGION:INSTANCE_NAME' # Replace with actual values
  _BACKEND_URL: 'https://backend-xxxxx-xx.a.run.app' # Replace after first backend deployment

options:
  logging: CLOUD_LOGGING_ONLY
  machineType: 'E2_HIGHCPU_8'

images:
  - 'asia-south2-docker.pkg.dev/$PROJECT_ID/myfirstproject-repo/backend:$COMMIT_SHA'
  - 'asia-south2-docker.pkg.dev/$PROJECT_ID/myfirstproject-repo/backend:latest'
  - 'asia-south2-docker.pkg.dev/$PROJECT_ID/myfirstproject-repo/frontend:$COMMIT_SHA'
  - 'asia-south2-docker.pkg.dev/$PROJECT_ID/myfirstproject-repo/frontend:latest'
